apiVersion: apps/v1
kind: Deployment
metadata:
  name: <+stage.variables.color>-deployment
  labels:
    harness.io/color: <+stage.variables.color>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <+stage.variables.app>
      version: <+stage.variables.color>
  template:
    metadata:
      labels:
        app: <+stage.variables.app>
        version: <+stage.variables.color>
    spec:
      containers:
        - name: <+stage.variables.app>-<+stage.variables.color>
          image: 688567283917.dkr.ecr.us-east-1.amazonaws.com/<+stage.variables.app_name>:<+stage.variables.version>
          ports:
            - containerPort: 8081
