apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${color}-deployment
  labels:
    harness.io/color: ${color}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${app_name}
      version: ${color}
  template:
    metadata:
      labels:
        app: ${app_name}
        version: ${color}
    spec:
      containers:
        - name: ${app_name}-${color}
          image: 688567283917.dkr.ecr.us-east-1.amazonaws.com/${app_name}:${version}
          ports:
            - containerPort: 8081
