apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marvel
      version: v1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: marvel
        version: v1
    spec:
      containers:
        - name: marvel-container1
          image: 688567283917.dkr.ecr.us-east-1.amazonaws.com/marvel:v1
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: deploy1-service
  annotations:
    harness.io/primary-service: "true"
    prometheus.io/scrape: "true"  # Enable scraping for this service
    prometheus.io/port: "9090"   
    
spec:
  selector:
    app: marvel
    version: v1 
  ports:
    - port: 80          # Exposed port on LoadBalancer
      targetPort: 8081  # The container port in the pod
  type: LoadBalancer

