apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: deploy1-split
  namespace: default
spec:
  service: deploy1-service
  backends:
  - service: deploy1-service
    weight: 80
  - service: deploy1-service-canary
    weight: 20
