replicaCount: 1

app:
  name: <+stage.variables.app>
  version: <+stage.variables.version>
  color: <+stage.variables.color>

image:
  repository: 688567283917.dkr.ecr.us-east-1.amazonaws.com/<+stage.variables.app>
  tag: <+stage.variables.version>
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 8081
