replicaCount: 1

app:
  name: marvel
  version: v1
  color: blue

image:
  repository: 688567283917.dkr.ecr.us-east-1.amazonaws.com/marvel
  tag: v1
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 8081
