apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
  labels:
    harness.io/color: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: marvel
      version: v1
  template:
    metadata:
      labels:
        app: marvel
        version: v1
    spec:
      containers:
        - name: marvel-blue
          image: 688567283917.dkr.ecr.us-east-1.amazonaws.com/marvel:v1
          ports:
            - containerPort: 8081
