apiVersion: v1
kind: Service
metadata:
  name: marvel-service-blue
  annotations:
    harness.io/primary-service: "true"
spec:
  selector:
    app: marvel
    version: blue
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.type }}
